spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bookstore?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 827428112mb
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.1.1
    port: 6379
#  activemq:
#    user: admin
#    password: admin
#    broker-url: tcp://127.0.0.1:61616
#    packages: trus-all=true
#  jms:
#    topic-name: topic
#    queue-name: queue
#  tengxun:
#    accessKey: AKIDQCznQoZqVv51wfnh2A3g9OO84lDP4gXC
#    secretKey: aGI6eweFi3VjiRv42kCjxxhsPismQq1x
#    bucket: test-1300625833
#    bucketName: test-1300625833
#    path: https://test-1300625833.cos.ap-guangzhou.myqcloud.com/
#    qianzhui:  test
#    area: ap-guangzhou
mybatis:
  mapper-locations: classpath*:mapper/*.xml
